### ISSUE TITLE
[SmartReact] Emoji images don't show on list command when they exist

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#161] opened 2018-12-25 08:48 UTC
# Command bugs

#### Command name

```
[p]react list
```

#### What cog is this command from?

`smartreact`

#### What were you expecting to happen?

The list showing the images of all the existing emojis with smart reacts after a reload (IDs are matching).

#### What actually happened?

Custom emojis only show the tag such as :renBan: or :shock: instead of the actual emoji.

#### How can we reproduce this issue?

```
[p]react list
```

After changing an emoji that has a smart reaction.

**Comment by Injabie3** [comment] 2020-06-17 05:44
So this also occurs on V3. I don't recall the exact root cause for it, but it was something along the lines of the `<:id:name:>` of one emoji was incorrect, and caused the rest to not show up. Would have to check again on the weekend to be sure.

**Comment by Injabie3** [comment] 2022-06-11 17:06
Closing as unable to repro after switching new paginator. Only time it seems to show up now is when we have emojis that no longer exist.

**Closed as completed by Injabie3** 2022-06-11 17:06 UTC
